# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://smallclover.github.io
date_format: "ordinal"
title: smallclover
subtitle: "每个程序员都是一位充满幻想的魔法师"
description: "smallclover的个人博客"
keywords: smallclover
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 1

# ---------------- #
#      Author      #
# ---------------- #
author: smallclover
organization: 未来道具研究所 
organization_url: https://github.com/Future-Gadget-Laboratory
location: tokyo, Japan
email: 18363998103@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 书籍

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
repository: smallclover/smallclover.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: mzlogin
    repo: blog-comments
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: smallclover
    repo: blog-comments
    clientID: bf937482c71cbfb0affa
    clientSecret: e8268a58c3b8ee332605bbac02b8545889b5add7
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
