# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.smallclover.com
date_format: "ordinal"
title: smallclover
subtitle: "每个程序员都是一位充满幻想的魔法师"
description: "smallclover的个人博客"
keywords: smallclover
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 1

# ---------------- #
#      Author      #
# ---------------- #
author: smallclover
organization: 未来道具研究所 
organization_url: https://github.com/Future-Gadget-Laboratory
location: tokyo, Japan
email: 18363998103@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: smallclover
douban_username: smallclover
facebook_username: smallclover
weibo_username: smallclover
zhihu_username: smallclover
twitter_username: smallclover

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: 王顺
disqus_username: smallclover

# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [JavaWeb, DataBase, SSH, Design Patterns]
skill_mobile_app_keywords: [Android]
